db_arnoldb:
  image: postgres:9.4
  environment:
    POSTGRES_DB: arnold

arnoldb:
  image: registry.namely.tech/namely/arnoldb:afe92fa4
  ports:
    - "8080"
  environment:
    PG_USER: postgres
    PG_HOST: db_arnoldb
    PG_DBNAME: arnold
    STORAGE_ENGINE: postgres
  links:
    - db_arnoldb

redis:
  image: redis
  ports:
    - "6379"

test:
  build: .
  dockerfile: Dockerfile-dev
  command: bash -c "bundle exec rspec"
  working_dir: /arnoldb_gem
  volumes: 
    - .:/arnoldb_gem
  environment:
    REDIS_URL: "redis://redis:6379"
    ARNOLDB_ADDR: arnoldb
    ARNOLDB_PORT: 8080
  links:
    - arnoldb
    - redis
